apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-downloader-api
  namespace: social-downloader
  labels:
    app: social-downloader-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: social-downloader-api
  template:
    metadata:
      labels:
        app: social-downloader-api
    spec:
      containers:
      - name: social-downloader-api
        image: ghcr.io/yourusername/social-downloader-api:latest
        ports:
        - containerPort: 2500
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: social-downloader-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: social-downloader-config
              key: PORT
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: social-downloader-config
              key: HOST
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: social-downloader-config
              key: LOG_LEVEL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: social-downloader-secrets
              key: JWT_SECRET
        - name: TWITTER_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: social-downloader-secrets
              key: TWITTER_BEARER_TOKEN
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: social-downloader-config
              key: CORS_ORIGINS
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /live
            port: 2500
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 2500
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: downloads-volume
          mountPath: /app/downloads
      volumes:
      - name: downloads-volume
        emptyDir: {}
      restartPolicy: Always
